### ISSUE TITLE
eventhough we added CSR-signed field, its throw error

### ISSUE THREAD

**Issue by Thamizhanaruldass** [onekicktech/inregistry-registrars-whmcs-module#1]
I have filled all fields in that module, but trying to save it throws the error 
"Missing IN Registry Signed Certificate. Please navigate to Configuration () > System Settings > Domain Registrars to configure.
Your changes have not been saved"

I uploaded the certificate in the same inregistry directory, then why I'm getting the error?

Thanks
Aruldass
![inregistry errro](https://github.com/onekicktech/inregistry-registrars-whmcs-module/assets/61128847/82ec8724-9cd5-4dc4-9899-067826a45770)

**Comment by kevinpareek** [comment]
Hello sir,

You need to upload signed certificate on your hosting and submit valid path of your file and try.

**Comment by Thamizhanaruldass** [comment]
Hi,
Thanks for your prompt reply, I have added it as you said now it's working thank you :).
![working](https://github.com/onekicktech/inregistry-registrars-whmcs-module/assets/61128847/891a88c5-9d70-43dd-bf69-b3bc096e54ff)
