### ISSUE TITLE
its not working getting code 0 error

### ISSUE THREAD

**Issue by todaysprint** [onekicktech/inregistry-registrars-whmcs-module#2]
Upon attempting to connect to tlsv1.2://[epp.ote.example.in:700](http://epp.ote.example.in:700/), we encountered the following error message: '' (code 0). We have attempted to use the credentials from our previous correspondence, but this hasn't resolved the issue.

can you help us to overcome

**Comment by kevinpareek** [comment]
hello @todaysprint 

please check 
`openssl s_client -connect epp.ote.registry.in:700`

let me know and also please share me error log so i can help you
